import Navbar from '@/components/Navbar/Navbar';
import MuiThemeProvider from '@/theme/theme';
export const metadata = {
  title: 'RepoQuest',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body style={{ padding: 0, margin: 0 }}>
        {/* <Providers> */}
        <MuiThemeProvider>
          <Navbar />
          {children}
        </MuiThemeProvider>
        {/* </Providers> */}
      </body>
    </html>
  );
}
