import Navbar from '@/components/Navbar/Navbar';

export const metadata = {
  title: 'RepoQuest',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body style={{ padding: 0, margin: 0 }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
