name: Auto Version and npm Install

on:
  push:
    branches:
      - master  # Adjust this to the branch you want to trigger the workflow on

jobs:
  auto_version_and_npm_install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"

      - name: Get previous tag
        id: previous_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags || echo 0.0.0)

      - name: Calculate new version
        id: calculate_version
        run: |
          PREVIOUS_TAG=${{ steps.previous_tag.outputs.tag }}
          IFS='.' read -ra VERSION_PARTS <<< "$PREVIOUS_TAG"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo ::set-output name=new_version::$NEW_VERSION

      - name: Commit version bump
        id: commit_version
        run: |
          NEW_VERSION=${{ steps.calculate_version.outputs.new_version }}
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      - name: Set new version as an output
        id: set_output_version
        run: echo ::set-output name=version::${{ steps.calculate_version.outputs.new_version }}
      
      - name: Display the new version
        run: echo "New version: ${{ steps.calculate_version.outputs.new_version }}"
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change this to the Node.js version you need
      
      - name: npm install
        run: npm install
